package de.spiel.GUI;

import javax.swing.table.DefaultTableModel;

import de.spiel.Spiel;

import java.awt.Window.Type;

/**
 * 
 * @author Fabian Angst
 */
public class SelectPlayerView extends javax.swing.JFrame
{

    /**
	 * 
	 */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form SelectPlayerView
     */
    public SelectPlayerView()
    {
	setAlwaysOnTop(true);
	setType(Type.UTILITY);
	setResizable(false);
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

	panTop = new javax.swing.JPanel();
	lblSpieleranzahl = new javax.swing.JLabel();
	spinnerSpieleranzahl = new javax.swing.JSpinner();
	btnOK = new javax.swing.JButton();
	btnSpielBeginnen = new javax.swing.JButton();
	btnSpielBeginnen.setEnabled(false);
	panCont = new javax.swing.JPanel();
	jScrollPane1 = new javax.swing.JScrollPane();
	tablePlayers = new javax.swing.JTable();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	setTitle("Ebbelwoi Unternehmensplanspiel - Spieleranzahl wählen");

	lblSpieleranzahl.setText("Spieleranzahl:");
	panTop.add(lblSpieleranzahl);

	spinnerSpieleranzahl.setModel(new javax.swing.SpinnerNumberModel(2, 2,
		5, 1));
	panTop.add(spinnerSpieleranzahl);

	btnOK.setText("OK");
	btnOK.addActionListener(new java.awt.event.ActionListener()
	{
	    public void actionPerformed(java.awt.event.ActionEvent evt)
	    {
		btnOKActionPerformed(evt);
	    }
	});
	panTop.add(btnOK);

	btnSpielBeginnen.setText("Spiel Beginnen");
	btnSpielBeginnen.addActionListener(new java.awt.event.ActionListener()
	{
	    public void actionPerformed(java.awt.event.ActionEvent evt)
	    {
		btnSpielBeginnenActionPerformed(evt);
	    }
	});
	panTop.add(btnSpielBeginnen);

	getContentPane().add(panTop, java.awt.BorderLayout.PAGE_START);

	panCont.setLayout(new java.awt.BorderLayout());

	tablePlayers.setModel(new javax.swing.table.DefaultTableModel(
		new Object[][] {

		}, new String[] { "#", "Spielername", "Kredit",
			"Kreditbetrag in € (max. 100.000)" })
	{
	    Class[] types = new Class[] { java.lang.Integer.class,
		    java.lang.String.class, java.lang.Boolean.class,
		    java.lang.Integer.class };
	    boolean[] canEdit = new boolean[] { false, true, true, true };

	    public Class getColumnClass(int columnIndex)
	    {
		return types[columnIndex];
	    }

	    public boolean isCellEditable(int rowIndex, int columnIndex)
	    {
		return canEdit[columnIndex];
	    }
	});
	jScrollPane1.setViewportView(tablePlayers);
	if (tablePlayers.getColumnModel().getColumnCount() > 0) {
	    tablePlayers.getColumnModel().getColumn(0).setMinWidth(15);
	    tablePlayers.getColumnModel().getColumn(0).setPreferredWidth(15);
	    tablePlayers.getColumnModel().getColumn(0).setMaxWidth(25);
	    tablePlayers.getColumnModel().getColumn(1).setMinWidth(55);
	    tablePlayers.getColumnModel().getColumn(1).setPreferredWidth(75);
	    tablePlayers.getColumnModel().getColumn(1).setMaxWidth(150);
	    tablePlayers.getColumnModel().getColumn(2).setMinWidth(35);
	    tablePlayers.getColumnModel().getColumn(2).setPreferredWidth(35);
	    tablePlayers.getColumnModel().getColumn(2).setMaxWidth(45);
	    tablePlayers.getColumnModel().getColumn(3).setMinWidth(180);
	    tablePlayers.getColumnModel().getColumn(3).setPreferredWidth(180);
	    tablePlayers.getColumnModel().getColumn(3).setMaxWidth(230);
	}

	panCont.add(jScrollPane1, java.awt.BorderLayout.CENTER);

	getContentPane().add(panCont, java.awt.BorderLayout.CENTER);

	pack();
    }// </editor-fold>

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt)
    {
	fillTable();
    }

    private void btnSpielBeginnenActionPerformed(java.awt.event.ActionEvent evt)
    {
	performStart();
    }

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[])
    {
	/* Set the Nimbus look and feel */
	// <editor-fold defaultstate="collapsed"
	// desc=" Look and feel setting code (optional) ">
	/*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase
	 * /tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
		    .getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger
		    .getLogger(SelectPlayerView.class.getName()).log(
			    java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger
		    .getLogger(SelectPlayerView.class.getName()).log(
			    java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger
		    .getLogger(SelectPlayerView.class.getName()).log(
			    java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger
		    .getLogger(SelectPlayerView.class.getName()).log(
			    java.util.logging.Level.SEVERE, null, ex);
	}
	// </editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable()
	{
	    public void run()
	    {
		new SelectPlayerView().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSpielBeginnen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSpieleranzahl;
    private javax.swing.JPanel panCont;
    private javax.swing.JPanel panTop;
    private javax.swing.JSpinner spinnerSpieleranzahl;
    private javax.swing.JTable tablePlayers;
    // End of variables declaration

    // Code
    private DefaultTableModel model;

    private void fillTable()
    {
	model = (DefaultTableModel) tablePlayers.getModel();
	int c = Integer.parseInt(spinnerSpieleranzahl.getValue().toString());
	model.setRowCount(0);
	for (int i = 0; i < c; i++) {
	    model.addRow(new Object[] { i + 1, "Spieler " + (i + 1), false,
		    null });
	}
	btnSpielBeginnen.setEnabled(true);
    }

    private void performStart()
    {
	int c = model.getRowCount();
	String[] namen = new String[c];
	boolean[] kredit = new boolean[c];
	int[] kreditBetrag = new int[c];

	for (int i = 0; i < c; i++) {
	    namen[i] = tablePlayers.getValueAt(i, 1).toString();
	    kredit[i] = Boolean.valueOf(tablePlayers.getValueAt(i, 2)
		    .toString());

	    if ("true".equals(tablePlayers.getValueAt(i, 2).toString())) {
		// bei fehlerhafter eingabe eines kreditbetrags (nullpointer)
		// wird der betrag automatisch auf 0 gesetzt
		try {
		    int betrag = Integer.parseInt(tablePlayers.getValueAt(i, 3)
			    .toString());
		    if (betrag > 100000) {
			betrag = 100000;
			kreditBetrag[i] = betrag;
		    } else {
			kreditBetrag[i] = betrag;
		    }

		} catch (Exception e) {
		    kreditBetrag[i] = 0;
		}

	    } else {
		kreditBetrag[i] = 0;
	    }
	}

	// Spiel.
	    Spiel s = new Spiel();
	    Spiel.startSpielFromGui(c, namen, kredit, kreditBetrag);
	    System.out.println(s.getSpieler().toString());
	    this.setVisible(false);
    }
    // End of Code
}